### ISSUE TITLE
Boot from ipxe failed on Dell R710

### ISSUE THREAD

**Issue by Gary15** [RackHD/RackHD#52] opened 2015-12-21 08:05 UTC
When I finished deploy the RackHD server by following https://github.com/RackHD/RackHD/blob/master/example/README.md. And it can demo successfully.Then I change the VM the network Adapter to Brideged Adapter.Connect it to Dell Server(R710). It gets stuck in **"Try to free Memory without Signature"**.Just like the picture show.
https://goo.gl/photos/hSecwSJQu8aQdnmz7

**Comment by heckj** [comment] 2015-12-22 18:54
There's an internal/NAT adapter which gives the RackHD VM access to the internet through your local machine, and a second adapter which is connect to the "closed-net" private host-only network. If you want to connect the RackHD instance to a local network connection to support PXE booting on that network connection, you'll need to update the second NIC from closed-net to bridged.

Given the picture showing a system PXE booting, it looks like you've got that connected successfully, but wanted to make sure.

The `Try to free Memory without Signature` message is coming from the embedded Broadcom PXE code - the ipxe development team has seen this issue in the past as well, and it seems to be an issue with the broadcom iPXE stack loading of the network provided iPXE. See 
 - http://lists.ipxe.org/pipermail/ipxe-devel/2012-August/001766.html 
 - http://lists.ipxe.org/pipermail/ipxe-devel/2012-August/001789.html
for some relevant messages if you're interested in the low-level details.

We haven't explicitly tested the Dell R710, but we have seen these kinds of issues before with embedded PXE in the NIC and memory constraints when loading PXE.

Possible work-arounds to this issue are using a different version of iPXE for your default setup. We built and provide iPXE from the ansible-based mechanisms in https://github.com/RackHD/on-imagebuilder. Right now it's set to build from the committish: 28149d30f56113f1047a7a348a67bd3e854fe4c0 from ipxe.org, you might try changing that value to "master" in https://github.com/RackHD/on-imagebuilder/blob/master/vars/ipxe.yml, building iPXE, and seeing if the resulting file works more effectively.

**Comment by Gary15** [comment] 2015-12-23 09:19
@heckj  I already changed the second NIC from closed-net to bridged.I am sure the server can get the service from the RackHD server.Cause I have tested a VM with the NIC Adapter is Brideged Adapter , and that VM can demo normally.
---

And I am trying to choose another server(DELL R610) to test , this error are gone.But it get stuck in another place.It doesn't look like a error You can get the information from the picture.
https://goo.gl/photos/4BWb6Sid4QoGUU13A

**Comment by heckj** [comment] 2015-12-23 16:23
I'm much less sure what's hanging there, or if it is hanging. It looks like the initrd kernel isn't completing its boot up on the R610. We have used R610's internally, and know they're working (although if you go to install ESXi on them, they need a custom driver set).

You may have run into the same issue @stevemendes did when we was trying to boot and load a Cisco UCS setup. We provided him with microkernels built on physical machines, and it booted right though. Something in our microkernel building process may not (haven't verified) be including all relevant drivers when created in VM's or using cloud resources.

I have older microkernels in a zip file, let me get those available for you to try and let's see if those resolve the issue for you. I'll follow up in comment here with a dropbox link where you can download a zip file to try.

**Comment by heckj** [comment] 2015-12-23 16:51
Hey @Gary15, I've got the older microkernel files in a zip file at https://www.dropbox.com/s/ph372nd29fw320s/old_microkernel.zip?dl=0 that you can download. Replace the files in your VM at /home/vagrant/src/on-http/static/http/common/ with these files, and let's see if that resolves the issue.

I opened a bug specifically for this issue (assuming it works for you) - but also because we saw this with another system and I didn't open it earlier: #57 .

Hopefully this helps resolve - please let me know.

**Comment by Gary15** [comment] 2015-12-25 07:34
Thanks, @heckj .The microkernel worked successfully. The discovery task can be done.I am trying to write the json file to install the OS. Any suggestion would be grateful.

**Comment by anhou** [comment] 2015-12-25 08:16
@Gary15 @heckj  I see the issue 'Try to free Memory without Signature". I also face this before, a possiable alternate way is to use undionly.kpxe. just rename undionly.kpxe to monorail.ipxe than overwrite monorail.ipxe in directory /var/renasar/on-tftp/static/tftp/, then have a try

**Comment by heckj** [comment] 2016-01-04 17:17
Given that the alternative worked, I'll close our this issue as a functional a duplicate of #57.

For the workflow, there's examples in the code base that are great to follow, and if you want something to "just install directly when it first finds a machine", then I'd recommend looking at the example in the VM based demo that installs CentOS and make some minor tweaks to install your preferred OS. In that case, you'd want to have both a sku definition (https://github.com/RackHD/RackHD/blob/master/example/samples/virtualbox_sku.json) and a workflow that it invokes when the SKU is identified (https://github.com/RackHD/RackHD/blob/master/example/samples/virtualbox_install_coreos.json)

**Closed by heckj** 2016-01-04 17:17 UTC
Labels: help wanted
