### ISSUE TITLE
[1.2] 1.1/templates/library no longer accepts switch config files

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#248] opened 2016-05-31 16:28 UTC
Starting on Friday (5/27), I get an unexpected error on the 1.2 branch.  When I try to add a template to the library using PUT /api/1.1/templates/library I get the following error:

```
onrack@ora:~$ curl -X PUT -H "Content-Type: application/octet-stream" --data-binary @/home/onrack/switch-config-A localhost:8080/api/1.1/templates/library/switch-config-A
TypeError: Object <br>!Command: show running-config<br>!Time: Wed May 18 19:53:59 2016<br><br>version 7.0(3)I2(2c)<br>switchname TestA <br><br>feature bash-shell<br>feature scp-server<br><br>interface Ethernet1/1<br><br>interface Ethernet1/2<br><br>interface Ethernet1/3<br><br>interface Ethernet1/4<br><br>interface Ethernet1/5<br><br>interface Ethernet1/6<br><br>interface Ethernet1/7<br><br>interface Ethernet1/8<br><br>interface Ethernet1/9<br><br>interface Ethernet1/10<br><br>interface Ethernet1/11<br><br>interface Ethernet1/12<br><br>interface Ethernet1/13<br><br>interface Ethernet1/14<br><br>interface Ethernet1/15<br><br>interface Ethernet1/16<br><br>interface Ethernet1/17<br><br>interface Ethernet1/18<br><br>interface Ethernet1/19<br><br>interface Ethernet1/20<br><br>interface Ethernet1/21<br><br>interface Ethernet1/22<br><br>interface Ethernet1/23<br><br>interface Ethernet1/24<br><br>interface Ethernet1/25<br><br>interface Ethernet1/26<br><br>interface Ethernet1/27<br><br>interface Ethernet1/28<br><br>interface Ethernet1/29<br><br>interface Ethernet1/30<br><br>interface Ethernet1/31<br><br>interface Ethernet1/32<br><br>interface Ethernet1/33<br><br>interface Ethernet1/34<br><br>interface Ethernet1/35<br><br>interface Ethernet1/36<br><br>interface Ethernet1/37<br><br>interface Ethernet1/38<br><br>interface Ethernet1/39<br><br>interface Ethernet1/40<br><br>interface Ethernet1/41<br><br>interface Ethernet1/42<br><br>interface Ethernet1/43<br><br>interface Ethernet1/44<br><br>interface Ethernet1/45<br><br>interface Ethernet1/46<br><br>interface Ethernet1/47<br><br>interface Ethernet1/48<br><br>interface Ethernet1/49<br><br>interface Ethernet1/50<br><br>interface Ethernet1/51<br><br>interface Ethernet1/52<br><br>interface Ethernet1/53<br><br>interface Ethernet1/54<br><br>interface mgmt0<br> &nbsp;ip address 192.168.200.240/24<br>line console<br>line vty<br>boot nxos bootflash:/nxos.7.0.3.I2.2c.bin <br><br><br> has no method &#39;on&#39;<br> &nbsp; &nbsp;at TemplateService.DbRenderableContentService.put (/var/renasar/on-http/node_modules/on-core/lib/common/db-renderable-content.js:139:16)<br> &nbsp; &nbsp;at /var/renasar/on-http/lib/api/1.1/northbound/templates.js:85:23<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/renasar/on-http/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/var/renasar/on-http/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at /var/renasar/on-http/node_modules/body-parser/lib/read.js:129:5<br> &nbsp; &nbsp;at invokeCallback (/var/renasar/on-http/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/var/renasar/on-http/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/var/renasar/on-http/node_modules/body-parser/node_modules/raw-body/index.js:308:7)<br> &nbsp; &nbsp;at IncomingMessage.EventEmitter.emit (events.js:92:17)<br> &nbsp; &nbsp;at _stream_readable.js:920:16<br> &nbsp; &nbsp;at process._tickDomainCallback (node.js:459:13)
```

This same command (with the same file) works on builds prior to Friday as well as on a recent build from the master branch.

**Comment by johren** [comment] 2016-05-31 16:47
From the on-http.log file:

interface Ethernet1/53

interface Ethernet1/54

interface mgmt0
  vrf member management
  ip address 192.168.219.240/24
line console
line vty
boot nxos bootflash:/nxos.7.0.3.I2.2c.bin


 has no method 'on'
    at TemplateService.DbRenderableContentService.put (/var/renasar/on-http/node_modules/on-core/lib/common/db-renderable-content.js:139:16)
    at /var/renasar/on-http/lib/api/1.1/northbound/templates.js:85:23
    at Layer.handle [as handle_request] (/var/renasar/on-http/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/renasar/on-http/node_modules/express/lib/router/route.js:131:13)
    at /var/renasar/on-http/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/var/renasar/on-http/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/var/renasar/on-http/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/var/renasar/on-http/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)

**Comment by benbp** [comment] 2016-05-31 18:24
@johren I think what's happening here is you have on-http/node_modules/on-core on the master branch, but on-http on the 1.2 branch. You'll notice the traceback points to line 139 of the db-renderable-content.js file (https://github.com/RackHD/on-core/blob/master/lib/common/db-renderable-content.js#L139), which doesn't exist on 1.2 (https://github.com/RackHD/on-core/blob/release/1.2.0-branch/lib/common/db-renderable-content.js#L135).

On master in the templates API, we pass a stream object as the second argument into the DbRenderableContent.put call (https://github.com/RackHD/on-http/blob/master/lib/api/1.1/northbound/templates.js#L84), but in 1.2, we instead pass a string (https://github.com/RackHD/on-http/blob/release/1.2.0-branch/lib/api/1.1/northbound/templates.js#L85).

I'm pretty sure this is what you are seeing, so I'm going to close this, but feel free to re-open if you think it's a different root cause.

**Closed by benbp** 2016-05-31 18:24 UTC
Labels: bug
