### ISSUE TITLE
monorail-undionly.kpxe file does not work with virtualbox pie clients with --ioapic enabled

### ISSUE THREAD

**Issue by kacole2** [RackHD/RackHD#192] opened 2016-04-21 16:17 UTC
This is issue is being created in regards to the Slack conversations. RackHD is not executing the PXE booting process of an image from workflows.

This behavior is being seen in the Vagrant image 0.13 when following steps 2-12 in [Docker Machine Driver for RackHD Vagrant Example](https://github.com/emccode/machine/tree/master/rackhd). Do not perform this `git checkout d3e545a1e`.

Once the machine retrieve an IP address via DHCP it starts the RackHD process but falls short with the error on the screen of `No bootable device`. 
![Imgur](http://i.imgur.com/XJ3D7DQ.png)

The error log in RackHD says (from [gist](https://gist.github.com/kacole2/eb0d480ea4ca83e65670c5c4c1b7fc75#file-gistfile1-txt-L3875)): 
```
21:39:47 graph.1  |  [info] [2016-04-20T21:39:47.611Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Running task
21:39:47 graph.1  |   -> /lib/task-runner.js:340
21:39:47 graph.1  |  taskRunnerId: c5a832a0-4b74-476d-9ff1-578fab3a7e38
21:39:47 graph.1  |  taskId:       3f0a2049-9aa9-4b28-afa5-0f88c25bd045
21:39:47 graph.1  |  taskName:     Task.Os.Install.CentOS
21:39:47 graph.1  |  [info] [2016-04-20T21:39:47.657Z] [on-taskgraph] [Task.Task] [Server] Running task job.
21:39:47 graph.1  |   -> /node_modules/on-tasks/lib/task.js:324
21:39:47 graph.1  |  taskId: 3f0a2049-9aa9-4b28-afa5-0f88c25bd045
21:39:47 graph.1  |  name:   Install CentOS
21:39:47 graph.1  |  job:    Job.Os.Install
21:39:53 dhcp.1   |  [warning] [2016-04-20T21:39:53.009Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Could not get TFTP bootfile name from active task. Sending default bootfile.
21:39:53 dhcp.1   |   -> /lib/message-handler.js:201
21:39:53 dhcp.1   |  error:
21:39:53 dhcp.1   |    message: Request Timed Out (on.task:methods.getBootProfile.5717f6d98f3a6b7e0969b7a8:Object).
21:39:53 dhcp.1   |    name:    RequestTimedOutError
21:39:53 dhcp.1   |    context:
21:39:53 dhcp.1   |  [warning] [2016-04-20T21:39:53.372Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Could not get TFTP bootfile name from active task. Sending default bootfile.
21:39:53 dhcp.1   |   -> /lib/message-handler.js:201
21:39:53 dhcp.1   |  error:
21:39:53 dhcp.1   |    message: Request Timed Out (on.task:methods.getBootProfile.5717f6d98f3a6b7e0969b7a8:Object).
21:39:53 dhcp.1   |    name:    RequestTimedOutError
21:39:53 dhcp.1   |    context:
```

If I turn off the PXE host and power it back on, then the PXE process of installation begins. However, It's not using the `centos-ks` file that has been modified to not do a graphical based installation. 

After further testing, I verified everything works as it should with Vagrant 0.11. Those commits are back from January.
```
/home/vagrant/src
61ec3e1ee2e6aca3e57ce222fbd10f0fdeca6ec1 Merge pull request #77 from RackHD/master_update
/home/vagrant/src/on-core
bbfcd725b91690a2a92a45031373053a6f6729c4 Merge pull request #67 from yyscamper/fix-houndci
/home/vagrant/src/on-dhcp-proxy
54e9086c7316d381a30cdf20679e4ccc527213bf Merge pull request #22 from yyscamper/fix-houndci
/home/vagrant/src/on-http
739503e59b361667c0639ad9f40fdbbd904b6155 Merge pull request #94 from yyscamper/fix-houndci
/home/vagrant/src/on-imagebuilder
4c867a9c0dcaa994fede0a13c8fce2ba9247015d Merge pull request #11 from RackHD/ipmitool-vers
/home/vagrant/src/on-syslog
19e13564b39419297f8a5a063ea0e5ed673991ed Merge pull request #15 from rolandpoulter/lodash-v3
/home/vagrant/src/on-taskgraph
3590148123ae4380cacc23e8573748880098b342 Merge pull request #50 from yyscamper/fix-houndci
/home/vagrant/src/on-tasks
72fb38ff8fd695529e01a183f8c782c0479db2e7 Merge pull request #110 from yyscamper/fix-houndci
/home/vagrant/src/on-tftp
a07063d5cafd29ba14b2becdca97bc7dfeb85939 Merge pull request #27 from yyscamper/fix-houndci
```

To replicate my steps first try with Vagrant 0.13 to see the errors, then perform the following:

1. Remove the latest vagrant image 0.13. `vagrant box remove rackhd/rackhd`
2. Add vagrant image 0.11. `vagrant box add rackhd/rackhd -c --box-version 0.11`
3. from the `RackHD/RackHD` repo, change the head to an older commit (not sure if this is really necessary) `git checkout d3e545a1e`
4. Follow all the steps 3-12 on here -> https://github.com/emccode/machine/tree/master/rackhd

cc @tgelter

**Comment by benbp** [comment] 2016-04-21 22:47
Adding some debugging progress info from Slack:

> 
benbp [3:39 PM] 
@joseph.heck @kenny @tgelter I've traced the client VM pxe timeout issue to the newer ipxe image we're building

[3:39] 
suspecting now it has something to do with the dhcp timeout changes

[3:39] 
it just goes DHCP DISCOVER -> DHCP OFFER and then dies, no DHCP REQUEST back

[3:39] 
I used an older build and everything worked

stu00 [3:44 PM] 
Those should only be impacted the proxy steps… and it makes those timeouts longer. (I’m not arguing that it’s happening, but it really shouldn’t…???)

[3:44] 
impacting.

benbp [3:45 PM] 
@stu00: yeah I feel the same way, but the only other change was copying and using the monorail-undionly.kpxe file. I thought I had tried a version pre-dating that, and then a version pre-dating your changes, but I can't be sure that that's accurate. What I can do is explicitly make three image builds from each commit, and try them all out

new messages
tgelter [3:46 PM] 
Sorry, was traveling from conference to home (and now leaving again)

[3:46] 
I’ll follow this convo later tonight hopefully, thanks

benbp [3:46 PM] 
the relevant two commits are https://github.com/RackHD/on-imagebuilder/commit/9ba817c7f4e9a2a6fd47c28e091694ae7edab6d3 and https://github.com/RackHD/on-imagebuilder/commit/bd8394bde42672cc12b48d18f8ba36348ede2e45
 
GitHub
Merge pull request #30 from stuart-stanley/cap-17-proxy-pxe-timeouts · RackHD/on-imagebuilder@9ba817c · GitHub
Raise dhcp-proxy timeout settings to spec to avoid timeouts in non-simple topologies.
 
GitHub
Merge pull request #32 from anhou/ipxe-undionly · RackHD/on-imagebuilder@bd8394b · GitHub
Fetch undionly.kpxe from ipxe

**Comment by benbp** [comment] 2016-04-21 22:52
Here's a packet trace of one of these failed boots (formatted for wireshark):

[dumpfile.zip](https://github.com/RackHD/RackHD/files/230861/dumpfile.zip)

If you follow you'll see a successfull DHCP boot and TFTP download from the stock PXE image on the VM, and then the start of another DHCP conversation from our ipxe image, which never gets past the DHCP REQUEST stage. The packets themselves look fine to me (though I could be mistaken), which is what leads me to believe it's an ipxe image issue.

**Comment by benbp** [comment] 2016-04-21 23:09
Ok it appears that the latest build of monorail.ipxe works fine with VirtualBox, but the monorail-undionly.kpxe does *not* work. So we could either figure out why this is, or figure out some way to differentiate virtual box clients and give them monorail.ipxe.

FYI @anhou @kacole2 @heckj

**Comment by benbp** [comment] 2016-04-21 23:10
@kacole2 I changed the PR title FYI

**Comment by benbp** [comment] 2016-04-21 23:39
Another detail here is that this works with the vBMC images, because they use qemu, but not a stock virtualbox VM.

**Comment by heckj** [comment] 2016-04-21 23:49
Virtualbox supports multiple pics, so one of these variants may also work or at least not report that it supports UNDIonly when it apparently doesn't:

![screen shot 2016-04-21 at 4 38 45 pm](https://cloud.githubusercontent.com/assets/43388/14727430/a8184f9e-07df-11e6-82a5-043e574da994.png)

I've found it working for me with the `Intel PRO/1000 MT Desktop (82540EM)` NIC on virtualbox

**Comment by benbp** [comment] 2016-04-21 23:50
Aaaaaand now things are working for me again, and not reproducing for @heckj either, making me doubt all my above conclusions...

**Comment by benbp** [comment] 2016-04-21 23:54
OK I have solid repro steps now though:

- Boot a virtualbox VM and discover it (this will work).
- Create OBM settings for the VM
- Run a CentOS installer workflow against (I assume any workflow would work)
- Reboot VM and watch boot hang

**Comment by benbp** [comment] 2016-04-22 00:03
Ok turns out if you actually shut down the VM, and boot it up, it works. If you just reboot it (like via command-R), then it won't work.

**Comment by benbp** [comment] 2016-04-22 00:25
More detailed repro (accounting for @heckj's non-repro):

- Boot a virtualbox VM and discover it
- Let it time out on the reboot:
![image](https://cloud.githubusercontent.com/assets/1020379/14728012/d21d0040-07e5-11e6-9dc9-4266281e4b4d.png)
- Create noop obm settings and run an OS installer workflow (likely inconsequential, any workflow will do)
- Reboot the VM (DO NOT shut it down, keep the console open and press command-R/ctrl-R)
- Watch the ipxe image time out on DHCP (Configuring net0...)

**Comment by anhou** [comment] 2016-04-22 07:07
@benbp  so the detailed reproduce steps is based on monorail-undionly.kpxe? and for monorail.ipxe don't have this problem with the reproduce steps ?

**Comment by anhou** [comment] 2016-04-22 09:46
@benbp I run simliar steps, also reboot virtualbox VM, not shutdown and powe on,
1.  Boot a virtualbox VM and discover it
2. Let it time out on the reboot: 
3. `'curl -X DELETE localhost:8080/api/1.1....' to delete the discovered node(just let pxe to load monorail-undionly.kpxe and bootup again, assume it's the same with a OS installer workflow, just as you said, it's likey inconsequential)`
4. Reboot the VM (DO NOT shut it down, keep the console open and press command-R/ctrl-R)
5. `ipxe boot successfully, and node is discovered again`

Assume the step 1-4 is the same with your steps, and it succeed as step5. maybe the vritualbox version is not different? the virtualbox version in my side is 4.3.36 and it's virtualbox in Linux, pxe-1's NIC is Intel PRO/1000 MT Desktop(82540EM)

**Comment by heckj** [comment] 2016-04-22 14:35
@anhou per your question above - the repro steps were with monorail-undionly.kpxe. When using monorail.ipxe, it appears to work correctly - the change to hand down a proper bootloader based on the DHCP packet information is what cascaded to this.

Just so it's down here, @benbp and I were both working against VirtualBox 5.0.16 r105871, and the nic in the PXE VM was the same - the 82540EM per the setup script at https://github.com/RackHD/RackHD/blob/master/example/bin/monorail_rack#L67

I'm going back in to repro some of this morning, and was going to try:
 - varying the nic to see if that had any difference on the bootloader operation
 - updating PXE build to the very latest
 - updating VirtualBox to 5.0.18 (although I don't think this last has much hope of sorting things)

I did do some digging through the VirtualBox changelogs. It's a very long shot, but a change reported for the 5.0.16 version was resolving a PXE related bug : https://www.virtualbox.org/ticket/13628, the content of which indicates that the PXE rom used was updated internal to VirtualBox, which may have some bearing on this (hence my plan of trying the very latest to see if there's some subtle conflict there)

It's not clear to me where the root cause of this lies, I just don't have the depth in the underlying code, so I'm trying to isolate out variables.

**Comment by heckj** [comment] 2016-04-22 15:45
I've let the system fall through to the `System Halted` state, and I expected failure, but I'm not seeing it. I still can't reproduce this issue. Per slack, I do have the `Oracle VM VirtualBox Extension Pack` loaded with my instance of virtualbox.

![screen shot 2016-04-22 at 8 32 49 am](https://cloud.githubusercontent.com/assets/43388/14746813/4c992a58-0866-11e6-9e3c-0743bab695bb.png)

@kacole2 reported on slack that he didn't have this loaded. Waiting to hear from @benbp on the same.

Per the VirtualBox Downloads page:

> VirtualBox 5.0.18 Oracle VM VirtualBox Extension Pack  All supported platforms 
> Support for USB 2.0 and USB 3.0 devices, VirtualBox RDP and PXE boot for Intel cards. See this chapter from the User Manual for an introduction to this Extension Pack. The Extension Pack binaries are released under the VirtualBox Personal Use and Evaluation License (PUEL).
> Please install the extension pack with the same version as your installed version of VirtualBox! 

I have the hypothesis that this is the significant difference. I am running through @kacole2's exact steps now to attempt to reproduce this issue again.

**Comment by heckj** [comment] 2016-04-22 18:55
I finally got a repro - @benbp did have the extension pack installed, so that's not the differentiating variable. By following @kacole2 setup and steps, I was able to see the failure scenario.

**Comment by heckj** [comment] 2016-04-22 19:13
Trying out latest iPXE (up to master) monorail-undionly.kpxe for this booting:

commit: `55e409b14fdfc6bcd51cdcdaf1ee20ad5258215d` from ipxe.org repository
```
md5sum /tmp/on-imagebuilder/ipxe_build_env/ipxe/src/bin/undionly.kpxe
2e095c29e23fabc0f184e175c5f6ed91  /tmp/on-imagebuilder/ipxe_build_env/ipxe/src/bin/undionly.kpxe
```

Upon clearing the nodes (via API) from RackHD and just a reset in VirtualBox (not powering down), the node will also not even boot the first time, so there's some state that isn't being cleared on reset.

Screenshot of failure with undionly.kpxe from master branch of ipxe.org:
![screen shot 2016-04-22 at 12 08 52 pm](https://cloud.githubusercontent.com/assets/43388/14752304/6d896706-0883-11e6-85dd-98e9285360c4.png)


I went ahead and verified that `monorail.ipxe` as opposed to `monorail-undionly.kpxe` does successfully boot - so in essence it appears that Virtual either 1) isn't clearing something correctly, or 2) isn't quite correct in it's support of the UNDIONLY architecture which we started responding to.

**Comment by heckj** [comment] 2016-04-22 19:34
- Original NIC configuration : `Intel PRO/1000 MT Desktop (82540EM)` failing
- Reconfigured back to failure scenario and updated the PXE VM to utilize the NIC adapter `Intel PRO/1000 T Server (82543GC)`. Result: *failure - same failure scenario*
- Reconfigured back to failure scenario and updated the PXE VM to utilize the NIC adapter `Intel PRO/1000 T Server (82545EM)`. Result: *failure - same failure scenario*
- Reconfigured back to failure scenario and updated the PXE VM to utilize the NIC adapter `PCnet-PCI II (Am79C970A)`. Result: *failure - same failure scenario*
- Reconfigured back to failure scenario and updated the PXE VM to utilize the NIC adapter `PCnet-FAST III (Am79C973)`. Result: *failure - same failure scenario*
- Reconfigured back to failure scenario and updated the PXE VM to utilize the NIC adapter `Paravirtualized Network (virtio-net)`. Result: This adapter doesn't support PXE booting at all, not surprisingly.

**Comment by heckj** [comment] 2016-04-22 19:52
As an experiment, I went ahead and removed the SKU I'd set up with @kacole2 instructions, and re-added the SKU definition and workflow from the CoreOS install example. After discovery completes, with no other changes, the node now fails to boot the OS. Since this worked as a starting point, it seems to indicate that there's something in the flow that's making a difference to this failure scenario:

The VM configuration is different:

Stock:
```
            VBoxManage createvm --name $vmName --register;
            VBoxManage createhd --filename $vmName --size 8192;
            VBoxManage storagectl $vmName --name "SATA Controller" --add sata --controller IntelAHCI
            VBoxManage storageattach $vmName --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $vmName.vdi
            VBoxManage modifyvm $vmName --ostype Ubuntu --boot1 net --memory 1024;
            VBoxManage modifyvm $vmName --nic1 intnet --intnet1 closednet --nicpromisc1 allow-all;
            VBoxManage modifyvm $vmName --nictype1 82540EM --macaddress1 auto;
```

@kacole2 setup from (https://github.com/emccode/machine/blob/master/rackhd/README.md)
```
          VBoxManage createvm --name $vmName --register;
          VBoxManage createhd --filename $vmName --size 8192;
          VBoxManage storagectl $vmName --name "SATA Controller" --add sata --controller IntelAHCI
          VBoxManage storageattach $vmName --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $vmName.vdi
          VBoxManage modifyvm $vmName --ostype Ubuntu --boot1 net --memory 1024 --cpus 2;
          VBoxManage modifyvm $vmName --nic1 intnet --intnet1 closednet --nicpromisc1 allow-all;
          VBoxManage modifyvm $vmName --nictype1 82540EM --macaddress1 auto;
          VBoxManage modifyvm $vmName --nic2 NAT;
          VBoxManage modifyvm $vmName --nictype2 82540EM --macaddress2 auto;
          VBoxManage modifyvm $vmName --natpf2 "guestssh,tcp,,2$i2$i,,22";
          VBoxManage modifyvm $vmName --ioapic on;
          VBoxManage modifyvm $vmName --rtcuseutc on;
```

**Comment by kacole2** [comment] 2016-04-22 19:55
@heckj yes, I was adding a secondary NIC for use with getting internet access. I don't know if a new version of  `monorail-undionly.kpxe` is prohibiting this behavior because it worked previously. thanks!

**Comment by heckj** [comment] 2016-04-22 20:15
The underlying code that's made the change to hand out `monorail-undionly.kpxe` was made to enable physical machines reporting UNDI support to boot, which don't always work consistently with `monorail.ipxe`. The work effort was in https://github.com/RackHD/on-dhcp-proxy/pull/30, relevant code at https://github.com/RackHD/on-dhcp-proxy/blame/master/lib/message-handler.js#L275-L308.

I captured packetData within that segment to see if there was anything useful as a VirtualBox identifier in that packet, but I'm afraid it's pretty damn sparse:

```
20:03:43 dhcp.1   |  [info] [2016-04-22T20:03:43.886Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] GOING TO REPLY WITH MONORAIL-UNDIONLY.KPXE BOOTLOADER:
20:03:43 dhcp.1   |   -> /lib/message-handler.js:306
20:03:43 dhcp.1   |  fname:
20:03:43 dhcp.1   |  op:
20:03:43 dhcp.1   |    value: 1
20:03:43 dhcp.1   |    name:  BOOTPREQUEST
20:03:43 dhcp.1   |  sname:
20:03:43 dhcp.1   |  magic:   1669485411
20:03:43 dhcp.1   |  flags:   0
20:03:43 dhcp.1   |  secs:    4
20:03:43 dhcp.1   |  options:
20:03:43 dhcp.1   |    dhcpMessageType:
20:03:43 dhcp.1   |      value: 3
20:03:43 dhcp.1   |      name:  DHCPREQUEST
20:03:43 dhcp.1   |    parameterRequestList:
20:03:43 dhcp.1   |      - 1
20:03:43 dhcp.1   |      - 2
20:03:43 dhcp.1   |      - 3
20:03:43 dhcp.1   |      - 4
20:03:43 dhcp.1   |      - 5
20:03:43 dhcp.1   |      - 6
20:03:43 dhcp.1   |      - 11
20:03:43 dhcp.1   |      - 12
20:03:43 dhcp.1   |      - 13
20:03:43 dhcp.1   |      - 15
20:03:43 dhcp.1   |      - 16
20:03:43 dhcp.1   |      - 17
20:03:43 dhcp.1   |      - 18
20:03:43 dhcp.1   |      - 22
20:03:43 dhcp.1   |      - 23
20:03:43 dhcp.1   |      - 28
20:03:43 dhcp.1   |      - 40
20:03:43 dhcp.1   |      - 41
20:03:43 dhcp.1   |      - 42
20:03:43 dhcp.1   |      - 43
20:03:43 dhcp.1   |      - 50
20:03:43 dhcp.1   |      - 51
20:03:43 dhcp.1   |      - 54
20:03:43 dhcp.1   |      - 58
20:03:43 dhcp.1   |      - 59
20:03:43 dhcp.1   |      - 60
20:03:43 dhcp.1   |      - 66
20:03:43 dhcp.1   |      - 67
20:03:43 dhcp.1   |      - 128
20:03:43 dhcp.1   |      - 129
20:03:43 dhcp.1   |      - 130
20:03:43 dhcp.1   |      - 131
20:03:43 dhcp.1   |      - 132
20:03:43 dhcp.1   |      - 133
20:03:43 dhcp.1   |      - 134
20:03:43 dhcp.1   |      - 135
20:03:43 dhcp.1   |    maximumMessageSize:    1260
20:03:43 dhcp.1   |    archType:              0
20:03:43 dhcp.1   |    vendorClassIdentifier: PXEClient:Arch:00000:UNDI:002001
20:03:43 dhcp.1   |  hlen:    6
20:03:43 dhcp.1   |  chaddr:
20:03:43 dhcp.1   |    type:
20:03:43 dhcp.1   |      value: 1
20:03:43 dhcp.1   |      name:  HW_ETHERNET
20:03:43 dhcp.1   |    address: 08:00:27:b3:ea:47
20:03:43 dhcp.1   |  hops:    0
20:03:43 dhcp.1   |  xid:     682879559
20:03:43 dhcp.1   |  ciaddr:  172.31.128.5
```

The only thing that seems like it might be possible to utilize is the UNDI major and minor version: `002` and `001` respectively, but I don't have any knowledge of if this represents VirtualBox explicitly from any other architectures where the original bug exhibited.

**Comment by heckj** [comment] 2016-04-22 20:27
More detail - I blew away the more complex configured VM and reset to the simpler demo set, and undionly worked reliably, which seems to be indicative of the VM configuration being the issue. 

I went and recreated the VM configuration per Kenny's instructions, and its definitely repeated - so something in that configuration appears to be critical to the reproduction. I'll continue to refine/bisect to determine.

**Comment by heckj** [comment] 2016-04-22 20:46
Found the mechanism that is the repeatable repro element: `VBoxManage modifyvm $vmName --ioapic on;`

Remove this from scripts and setup - default is off, or set it explicitly to `off` and you should be good.

**Closed** 2016-04-22 20:53 UTC
Labels: bug, help wanted

**Comment by anhou** [comment] 2016-04-26 07:43
@heckj Good find. from Vritualbox's Version 5.0.10's manual, it's still unstable for IO APIC
![image](https://cloud.githubusercontent.com/assets/14013330/14810395/532902a0-0bc5-11e6-9736-d3d7d44b4e87.png)
