### ISSUE TITLE
**CoreOS** could not complete when running Graph.InstallCoreOS

### ISSUE THREAD

**Issue by lanchongyizu** [RackHD/RackHD#403] opened 2016-09-04 13:41 UTC
When running the workflow Graph.InstallCoreOS, it could  not complete because the following two lines would never be touched.
https://github.com/RackHD/on-http/blob/master/data/templates/install-coreos.sh#L5-L6

```
wget --spider http://<%=server%>:<%=port%>/api/current/templates/<%=completionUri%>
sudo reboot
```

**Comment by tgelter** [comment] 2016-09-04 22:14
Probable duplicate of https://github.com/RackHD/RackHD/issues/398

**Comment by lanchongyizu** [comment] 2016-09-05 03:19
I also had tried to add 
`wget --spider http://<%=server%>:<%=port%>/api/current/templates/<%=completionUri%>`
before
`sudo coreos-install -d <%=installDisk%> -c pxe-cloud-config.yml -b <%=repo%>`
and the workflow could be completed.

**Comment by heckj** [comment] 2016-09-06 15:45
@lanchongyizu that generally indicates that this line

`sudo coreos-install -d <%=installDisk%> -c pxe-cloud-config.yml -b <%=repo%>` from https://github.com/RackHD/on-http/blob/master/data/templates/install-coreos.sh#L4 returned a failure code. 

Did you look in the logs on the OS to see why the failure occurred? `journalctl`

**Comment by amymullins** [comment] 2016-09-30 18:31
A jenkins job for CoreOS was recently added in to our OS Install Regression test suite.  @dalebremner can you help confirm if this is still an issue?

**Comment by leoyjchang** [comment] 2016-10-20 10:10
Hi, @dalebremner, are you able to confirm this issue during your OS installation regression work?

**Comment by BillyAbildgaard** [comment] 2016-11-08 13:56
The lines referenced in this issue were replaced with 
```
curl -X POST -H 'Content-Type:application/json' http://<%=server%>:<%=port%>/api/current/notification?nodeId=<%=nodeId%>
sudo reboot
```

The CoreOS install has been passing in our Continuous Testing and I haven't seen any issues through my manual testing either.  I believe this issue can be closed unless anyone here is still seeing this issue when running the latest master

**Comment by amymullins** [comment] 2016-11-10 14:21
@leoyjchang and @lanchongyizu , based on @BillyAbildgaard 's response, can this issue be closed?

**Comment by leoyjchang** [comment] 2016-11-14 16:29
Great work, thanks @BillyAbildgaard. Close this issue based on the testing result.

**Closed by leoyjchang** 2016-11-14 16:29 UTC
Labels: help wanted
