### ISSUE TITLE
PXE-E23: Client received TFTP error from server

### ISSUE THREAD

**Issue by victorfong** [RackHD/RackHD#32] opened 2015-12-11 16:58 UTC
Hi, we are trying to provision a physical server with RackHD and we received the following error:

Start PXE over IPv4
Station IP address is 172.31.128.3
Server IP address is 172.31.128.1
NBP filename is monorail-efi64-snponly.efi
NBP filesize is 0 Bytes
PXE-E23: Client received TFTP error from server

The node is not detected by the RackHD server afterward. 

Thanks,
Victor

**Comment by benbp** [comment] 2015-12-11 18:39
Just to double check, do you have a file called monorail-efi64-snponly.efi in the `static/tftp/` directory for the RackHD on-tftp service? If not, you'll want to put these files (https://bintray.com/rackhd/binary/on-imagebuilder/view#files/ipxe) in there.

Another note, we have an oustanding bug that is preventing RackHD from being able to PXE boot machines in UEFI mode, which it seems like your server is doing. You might also try configuring it to boot in BIOS legacy mode for the time being.

Let me know if either of these things mitigate the problem, otherwise I have some other guesses as well. Next time you do this, if you can capture the log output from the services that would be helpful. Thanks!

**Comment by meganmurawski** [comment] 2015-12-11 20:50
Thanks. It looks like we have the right files on the RackHD server. We also switched to boot in legacy BIOS on a different node, which is recognized by the server. 

Now the problem is that node has no OBM settings section, so we can't run workflows on it. We tried manually posting this config, but it doesn't seem to have worked. We see some of the iPXE dialog start, then "Renasar: Error occurred while preparing your iPXE profile: Unable to retrieve workflow properties. Booting to disk in 5 seconds..."

Any idea?

**Comment by benbp** [comment] 2015-12-11 21:08
What was the issue you ran into when trying to manually post the config?

**Comment by meganmurawski** [comment] 2015-12-11 22:02
The error above is what we're seeing on the node after POSTing the OBM config and attempting a workflow. On the server side, we see a lot of "Error running Child Process" from the IPMI tool.

**Comment by benbp** [comment] 2015-12-11 22:05
Ah ok, so you can successfully POST OBM settings to the node document. I misunderstood.

Can you paste the full traceback/error message you get from that "Error running Child Process" message?

**Comment by victorfong** [comment] 2015-12-14 14:56
Hi Ben,

Maybe we should describe our environment for you to better understand what we are trying to do.

At this point, we are have RackHD server running and we are trying to have that work with our Orange Box (http://cluster.engineering/ubuntu-orange-box/), which is supposed to have 10 Intel NUCs running. At this point, we have verified that the RackHD server can connect to the 10 Intel NUCs by the IP address provided by the DHCP service running on the RackHD server. I have also verified with the Orange Box Tech Support team that the IPMI services are all enabled on the Intel NUCs. However, when RackHD detects the NUCs, the nodes created on RackHD does not have the OBM setting.

We have turned off the UEFI boot setting as you suggested and only use the legacy boot setting.We also tried manually setting the OBM setting into RackHD but we are still receiving the same OBM setting not found error. It would be really helpful if we can have a quick call to discuss what we can try.

Thanks,
Victor

**Comment by heckj** [comment] 2015-12-14 15:01
Morning Victor,

I didn't think that NUC's supported IPMI. They do support AMT (which works like IPMI for what it enables, but is a very different protocol). RackHD doesn't have the support for automatically setting up OBM setting for systems with AMT support. 

I may be mistaken, as I've not worked with the Orange Box setup previously. The capability also requires hardware connectivity inside the "server" hardware so that the OS running on the motherboard can talk to the BMC. Can you try connecting into one of those NUC's with a running Linux and verifying that IPMI does exist by running a command such as `ipmitool chassis power status` and verifying that you're able to get output from it?

**Comment by victorfong** [comment] 2015-12-14 15:21
Hi Joe,

I think you are right. When we first purchased the Orange Box, we were given Intel AMT Credentials, so it’s likely that the NUCs only support AMT, but not IPMI. In that case, why should we set up the nodes?

Thanks,
Victor

**Comment by victorfong** [comment] 2015-12-14 18:38
Hi guys, 

I meant to say "How should we set up the nodes?" Is there a specific JSON object like OBM setting that we can post to the nodes? We just need help at making RackHD to work with AMT. 

Thanks,
Victor

**Comment by heckj** [comment] 2015-12-14 19:01
Hey @victorfong 

I'm digging up old notes for this. First, make sure you have `amttool` installed on your instance of RackHD - it's what RackHD uses to talk to AMT endpoints. `sudo apt-get install amtterm` on Ubuntu should do the trick. You'll need to dig out how to get it installed if you're hosting RackHD on anything else.

It's probably already enabled on your NUCs, but here's the notes for enabling AMT access on them:

# How to enable AMT

* Enter BIOS Setup.* Usually "F2"
* Enable AMTEnter ME Setup.
* Login, factory default password is "admin". --> depending on the box this may have been changed. Make sure to check
  * Enable AMT Management Reboot

There's an "AMT OBM manager" setting that you can set with a `PATCH` uri to `/api/1.1/nodes`. I don't have an example of it handy, but i'll see what I can dig up. The code that does all the AMT work (in case you're interested) is at https://github.com/RackHD/on-tasks/blob/master/lib/services/amt-obm-service.js, which looks like the options for it are `hostname` and `password`

**Comment by benbp** [comment] 2015-12-14 19:50
Looking at the code, the options are going to be `host` (rather than `hostname`) and `password`. So you should be able to issue a PATCH to /api/current/nodes/<nodeId>

```json
{
    service: 'amt-obm-service',
    config: {
        host: <amt ip>,
        password: <amt password>
    }
}
```

**Comment by victorfong** [comment] 2015-12-14 19:55
Thanks Ben! For the <AMT IP>, do you know if it should be a MAC address or an IP address? I’m asking because I’m wondering if the IP address should be the one assigned by the DHCP service, or if it’s a static IP or MAC address of the network adapter.

Thanks,
Victor

**Comment by benbp** [comment] 2015-12-14 19:59
I'm not sure if AMT does DHCP or not. If it does, you should be able to specify a mac address and we'll do the lookup dynamically before issuing any OBM calls. If it doesn't, then you'll want to statically configure the IP in the BIOS setup and use that for the OBM data.

**Comment by benbp** [comment] 2015-12-14 20:04
From reading this briefly (https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Fconfiguringtheintelamtipaddress.htm), it looks like for DHCP the AMT will share  the host's address? If this is the case, I think you'll want to configure it as a static IP if possible. The reason being that our DHCP server will likely expire the DHCP lease while the host is offline, meaning that the OBM service will only work if the host is actively renewing its lease.

**Comment by benbp** [comment] 2015-12-14 20:06
The other option would be to configure the lease timeout in the isc-dhcp-server config `/etc/dhcp.conf` (these options: https://github.com/RackHD/on-dhcp-proxy/blob/master/dhcpd.conf#L3-L4) to be very long or never expire, so that the mac->ip correlation with the shared network interface will continue to work even if the node is offline.

**Comment by victorfong** [comment] 2015-12-14 20:13
Thanks a lot, Ben!

Just to clarify, we need to follow these steps for each of the NUC:

  1.  Turn on the NUC
  2.  Look at the IP address of the NUC
  3.  PATCH the node on RackHD server
  4.  Turn off the NUC

After finishing these four steps, we should be all set to start using the nodes, correct?

Thanks,
Victor

**Comment by benbp** [comment] 2015-12-14 21:51
Digging a little more on the AMT docs, what I recommend you try is:

1. Turn on the NUC and go into the BIOS setup page
2. Configure AMT to DHCP in the BIOS
3. Note the MAC address of the NUC's network interface, and boot the node
4. PATCH the node using that MAC address
5. Hit `/api/current/lookups?q=<mac address>` and see if you get results
6. If you do, try running the `Graph.Reboot.Node` workflow against the node

**Comment by tysonmcnulty** [comment] 2015-12-15 15:57
Hey Ben, we're able to do steps 1-5, but `Graph.Reboot.Node` results in a `TaskError` because it's still expecting to boot through IPMI. The full error is:

```
taskError:
  name:          AssertionError
  expected:      true
  operator:      ==
  message:       Node should have OBM settings for service: ipmi-obm-service
  stack:
    - AssertionError: Node should have OBM settings for service: ipmi-obm-service
    -     at Object.module.exports.(anonymous function) [as ok] (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/assert-plus/assert.js:242:35)
    -     at AssertService.(anonymous function) [as ok] (/var/renasar/on-taskgraph/node_modules/on-core/lib/common/assert.js:30:28)
    -     at /var/renasar/on-taskgraph/node_modules/on-tasks/lib/jobs/obm-control.js:72:20
    -     at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    -     at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:503:31)
    -     at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:577:18)
    -     at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:128:12)
    -     at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    -     at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
    -     at process._tickDomainCallback (node.js:459:13)
  isOperational: true
graphInstance: de1aa33b-dd5f-47de-81b9-76b3b16f2e54
graphName:     Reboot Node
D 2015-12-15T15:50:41.944Z [on-taskgraph] [TaskGraph.TaskGraph] [c6b021] Stopping TaskGraph.
 -> /lib/task-graph.js:589
state:         failed
graphInstance: de1aa33b-dd5f-47de-81b9-76b3b16f2e54
graphName:     Reboot Node
```

A `GET` to our node returns this:
```
{
  "workflows": [],
  "catalogs": [],
  "autoDiscover": false,
  "config": {
    "host": "c0:3f:d5:63:fe:75",
    "password": "Password1+"
  },
  "createdAt": "2015-12-15T14:48:22.125Z",
  "identifiers": [
    "c0:3f:d5:63:fe:75"
  ],
  "name": "c0:3f:d5:63:fe:75",
  "obmSettings": [
    {
      "service": "amt-obm-service",
      "config": {
        "host": "c0:3f:d5:63:fe:75",
        "password": "Password1+"
      }
    }
  ],
  "service": "amt-obm-service",
  "sku": null,
  "status": "available",
  "type": "compute",
  "updatedAt": "2015-12-15T15:33:33.139Z",
  "id": "567028362d122e1f05c6b021"
}
```

(We tried a `PUT` to the `"obmSettings"` as well.)

**Comment by heckj** [comment] 2015-12-15 16:00
I'll need @benbp to verify, but I think you just ran into https://github.com/RackHD/RackHD/issues/35 - our workflows have defaulted to IPMI for all OBM interactions. They can be overridden in the workflow directly when calling it - and I suspect you'll need to do just that. You can see an example in #35 for what I did for a workaround for a "no-op" OBM setting. I think you'd just need to replace them same with the `amt-obm-service`.

**Comment by tysonmcnulty** [comment] 2015-12-15 21:29
Thanks, @heckj. We seem to have been hitting that issue, but we can get around it by calling it with the `amt-obm-service`, as they said:

```
curl -X POST -H "Content-Type: application/json" http://${SERVER_URI}:8080/api/common/nodes/${NODE_ID}/workflows -d '{"name":"Graph.Reboot.Node","options":{"defaults": {"obmServiceName": "amt-obm-service"}}}'
```

We also had to throw `amttool-tng` on the server. Now we're getting 401 Unauthorized back from the `Graph.Reboot.Node` workflow, even with the credentials correctly set in my node. Here's the trace:

```
I 2015-12-15T21:27:11.843Z [on-taskgraph] [TaskGraph.TaskGraph] [14e0d1] Task failure, stopping TaskGraph and remaining tasks/jobs.
 -> /lib/task-graph.js:457
taskError:
  stack:
    - Error: Unable to determine power state (## '172.31.128.33' :: AMT Remote Control
    -
    -   FAULT: 401 Unauthorized
    - ).
    -     at /var/renasar/on-taskgraph/node_modules/on-tasks/lib/services/amt-obm-service.js:54:17
    -     at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    -     at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:503:31)
    -     at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:577:18)
    -     at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:128:12)
    -     at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    -     at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
    -     at process._tickDomainCallback (node.js:459:13)
  message:
    """
      Unable to determine power state (## '172.31.128.33' :: AMT Remote Control

        FAULT: 401 Unauthorized
      ).
    """
  isOperational: true
graphInstance: 15910535-3d9c-46ad-a8ee-ddedd532fb70
graphName:     Reboot Node
```

**Comment by benbp** [comment] 2015-12-15 21:58
Are you able to run the amttool-tng binary manually and verify that the call works? Looks like an error with the tool itself, perhaps the IP is unreachable or the password is incorrect?

**Comment by tysonmcnulty** [comment] 2015-12-15 22:02
All we did when we installed it was check that running "`amttool-tng`" at the command line printed out its help text. Is there some additional verification we can do?

**Comment by tysonmcnulty** [comment] 2015-12-15 22:10
We've added `console.log(this.options)` at line 38 of `/var/renasar/on-taskgraph/node_modules/on-tasks/lib/services/amt-obm-service.js`, and we're seeing some console output:

```
{ delay: 500,
  retries: 6,
  config: { host: '...', password: '...' } }
```

The settings for `host` and `password` change to whatever we POST to the node. When e.g. the host is wrong, we get a 500 instead of a 401. But we get a 401 no matter what the password is--we're setting the same password that's required to log into MEBx (after a Ctrl-P from boot).

**Comment by heckj** [comment] 2015-12-15 22:44
You spotted where the error is - can you try running this directly:

`export AMT_TIMEOUT=3`
`export AMT_PASSWORD=_your_amt_password_here_`
`amttool-tng --force $HOSTNAME rem_control info`

and see if you get the same response? That's basically what the code is doing under the covers. We don't regularly test or use `amttool-tng` so it's quite possible the way you invoke that code has changed and we didn't realize it.

**Comment by tysonmcnulty** [comment] 2015-12-15 23:01
Thanks Joe! Here is what I get with your CLI:
```onrack@stack11-ora:~$ amttool-tng --force 172.31.128.4 rem_control info
## '172.31.128.4' :: AMT Remote Control
# Remote Control Info :: AMT Remote Control
  Powerstate:    	S0
  Watchdog Expired:	No
  Power Source:  	AC
  Remote Control Capabilities:
    Control Commands Supported	powerCycle powerDown powerUp reset
    IanaOemNumber		343
    Special Commands Supported	PXE-boot HD-boot CD-boot
    Special Commands (Oem)	IDER SOL BiosSetup
    SystemFirmwareCapabilities	LockKeyboard UserPasswordBypass ForcedProgressEvents ConfigurationDataReset VerbosityVerbose VerbosityQuiet VerbosityScreenBlank
```

**Comment by tysonmcnulty** [comment] 2015-12-15 23:03
Here is the amttool-tng info:
```
onrack@stack11-ora:~$ amttool-tng 172.31.128.4 info
Use of uninitialized value $cmd in lc at /usr/bin/amttool-tng line 1858.
Use of uninitialized value $params[1] in lc at /usr/bin/amttool-tng line 1867.
## '172.31.128.4'
Use of uninitialized value $sub_cmd in lc at /usr/bin/amttool-tng line 1709.
Use of uninitialized value $cmd in lc at /usr/bin/amttool-tng line 1711.
# General Info :: AMT General Info
  Hostname:  node4amt
  AMT version:  8.1.40
  Code Versions:
    Flash:            	8.1.40
    Netstack:         	8.1.40
    AMTApps:          	8.1.40
    AMT:              	8.1.40
    Sku:              	Intel_AMT_Pro
    VendorID:         	8086
    Build Number:     	1416
    Recovery Version: 	8.1.40
    Recovery Build Num:	1416
    Legacy Mode:      	False
  BIOS version:  	RKPPT10H.86A.0032.2014.0303.1322
  Provisioning mode:  Enterprise
  Provisioning state:  Post Provisioning (Operational Mode)
  Config Server (IP:port):  0:9971
  VLan:  Disabled
  Network State:  Enabled
  Enabled Interfaces:  WebUI, SerialOverLAN, IdeRedirection
  Password model:  Separate (the password of the network and the local interfaces are separate)
  Local 'admin' password:  changed from default
  Remote 'admin' password:  changed from default
  Security parameters:
    Enterprise Mode:  True
    TLS Enabled:  False
    HwCrypto Enabled:  True
    Provisioning State:  Post Provisioning (Operational Mode)
    Network Interface Enabled:  True
    SOL Enabled:  True
    IDER Enabled:  True
    FWUpdate Enabled:  False
    Link Is Up:  True
  IDE-R Sessions Log:  Empty
  ME Capabilities:
    CommonServices 	Enabled 	(ver.: 1.0)
    AMT            	Enabled 	(ver.: 8.1)
    SAL            	Enabled 	(ver.: 1.0)
    Reserved3      	Disabled	(ver.: 0.0)
    Reserved4      	Disabled	(ver.: 0.0)
  System UUID:  dfc89080-34d4-11e1-a06f-c03fd563fe75
Use of uninitialized value $cmd in lc at /usr/bin/amttool-tng line 1831.
Use of uninitialized value $sub_cmd in lc at /usr/bin/amttool-tng line 1832.
# Audit Info :: AMT General Info
  Audit Policy:
    AuditedAppID             	EventId                               	Flag
     Security Admin          	AMT Provisioning Started              	-
     Security Admin          	AMT Provisioning Completed            	-
     Security Admin          	ACL Entry Added                       	-
     Security Admin          	ACL Entry Modified                    	-
     Security Admin          	ACL Entry Removed                     	-
     Security Admin          	ACL Access with invalid credentials   	-
     Security Admin          	ACL Entry Enabled                     	-
     Security Admin          	TLS State Changed                     	-
     Security Admin          	TLS Server Certificate Set            	-
     Security Admin          	TLS Server Certificate Removed        	-
     Security Admin          	TLS Trusted Root Certificate Added    	-
     Security Admin          	TLS Trusted Root Certificate Removed  	-
     Security Admin          	TLS Pre-shared Key Set                	-
     Security Admin          	Kerberos Settings Modified            	-
     Security Admin          	Kerberos Master Key Modified          	-
     Security Admin          	Set realm Authentication mode         	-
     Security Admin          		18	-
     Security Admin          		19	-
     Remote Control Operation	Performed Power-Up                    	-
     Remote Control Operation	Performed Power-Down                  	-
     Remote Control Operation	Performed Power-Cycle                 	-
     Remote Control Operation	Performed Reset                       	-
     Remote Control Operation	Boot Options                          	-
     Redirection Manager     	IDE-R Session Opened                  	-
     Redirection Manager     	IDE-R Session Closed                  	-
     Redirection Manager     	IDE-R Enabled                         	-
     Redirection Manager     	IDE-R Disabled                        	-
     Redirection Manager     	SoL Session Opened                    	-
     Redirection Manager     	SoL Session Closed                    	-
     Redirection Manager     	SoL Enabled                           	-
     Redirection Manager     	SoL Disabled                          	-
     Redirection Manager     		8	-
     Redirection Manager     		9	-
     Redirection Manager     		10	-
     Redirection Manager     		11	-
     Redirection Manager     		12	-
     Firmware Update Manager 	Firmware Updated                      	-
     Firmware Update Manager 	Firmware Update Failed                	-
     Security Audit Log      	Security Audit Log Cleared            	-
     Security Audit Log      	Security Audit policy modified        	-
     Security Audit Log      	Security Audit Log Disabled           	-
     Security Audit Log      	Security Audit Log Enabled            	-
     Security Audit Log      	Security Audit Log Exported           	-
     Security Audit Log      	Security Audit Log Recovered (AMT 5.1+)	-
     Network Time            	AMT Time Set                          	-
     Wireless Configuration  		3	-
     Wireless Configuration  		4	-
   	29Wireless profile added                	-
   	29Wireless profile removed              	-
   	29Wireless profile updated              	-
   	29	3	-
   	29	4	-
   	30Wireless profile added                	-
   	30Wireless profile removed              	-
   	30Wireless profile updated              	-
  Audit Log Status:
    PercentageFree:	75
    NumberOfRecords:	563
    TimeOfLastRecord:	15/12/2015 21:36
    State:		NoKey
    MaxAllowedAuditors:	1
Use of uninitialized value $cmd in lc at /usr/bin/amttool-tng line 1239.
# Remote Control Info :: AMT Remote Control
  Powerstate:    	S0
  Watchdog Expired:	No
  Power Source:  	AC
  Remote Control Capabilities:
    Control Commands Supported	powerCycle powerDown powerUp reset
    IanaOemNumber		343
    Special Commands Supported	PXE-boot HD-boot CD-boot
    Special Commands (Oem)	IDER SOL BiosSetup
    SystemFirmwareCapabilities	LockKeyboard UserPasswordBypass ForcedProgressEvents ConfigurationDataReset VerbosityVerbose VerbosityQuiet VerbosityScreenBlank
```

**Comment by tysonmcnulty** [comment] 2015-12-15 23:06
So it looks like amttool-tng actually can communicate with the AMT of the NUC, but RackHD keeps getting 401 error for some reasons. Any clue? Thanks.

**Comment by benbp** [comment] 2015-12-16 00:52
@mattgam @jfrey either of you ever seen this `amttool 401 unauthorized` issue? ^^

**Comment by jfrey** [comment] 2015-12-16 06:17
Probably not setting the environment password in the way we would expect.

**Comment by tysonmcnulty** [comment] 2015-12-16 14:45
Hi, we saw that currently it's using `this.password` in `amt-obm-service.js` for the environment variable. We changed it to `this.options.config.password` and it appears to be doing something different.

**Comment by jfrey** [comment] 2015-12-16 14:48
The amt code is fairly old and hasn't been updated for awhile so that makes sense. What's the new behavior?

**Comment by tysonmcnulty** [comment] 2015-12-16 14:59
The node's going down, but it's not coming back up, and we're getting a timeout. Gonna try extending the lease of the IP as @benbp suggested a little earlier.

**Comment by jfrey** [comment] 2015-12-16 15:02
You may try running the power on and off workflows to verify the amt usage is correct as well in isolation.

On Dec 16, 2015, at 6:59 AM, tysonmcnulty <notifications@github.com<mailto:notifications@github.com>> wrote:


The node's going down, but it's not coming back up, and we're getting a timeout. Gonna try extending the lease of the IP as @benbp<https://github.com/benbp> suggested a little earlier.

**Comment by tysonmcnulty** [comment] 2015-12-16 15:10
`Graph.PowerOff.Node` and `Graph.PowerOn.Node` are working! The default and max lease are `600` and `7200`, which should be long enough for a reboot. What about the `AMT_TIMEOUT`; would it help to increase it?

**Comment by heckj** [comment] 2015-12-16 16:34
@tysonmcnulty I created https://github.com/RackHD/on-tasks/pull/93 to try and match what you saw that re-enabled this for you. Could you verify that's what you ended up changing?

**Comment by heckj** [comment] 2015-12-18 23:29
should be resolved with https://github.com/RackHD/on-tasks/pull/93

**Closed by heckj** 2015-12-18 23:29 UTC
Labels: help wanted
