### ISSUE TITLE
Unable to complete (at least) Graph.InstallCoreOS workflow

### ISSUE THREAD

**Issue by tgelter** [RackHD/RackHD#398] opened 2016-08-31 23:03 UTC
Hello,

Based on a conversation with @heckj on Slack, we've been experiencing issues with the Graph.InstallCoreOS workflow remaining in a Running status until it eventually times out.

The installation actually finishes (meaning, CoreOS is installed to local disk and my cloud-config is applied successfully, however, the web hook (if that's how ya'll refer to it) isn't executing properly.
Joseph believes this is due to the fact that the lookup data for the node isn't being populated, so the install-coreos.sh template can't be pulled down:
<img width="748" alt="screen shot 2016-08-31 at 4 22 26 pm" src="https://cloud.githubusercontent.com/assets/2048618/18149277/7f7400cc-6f9c-11e6-8508-249eb250f0d1.png">
<img width="736" alt="screen shot 2016-08-31 at 4 45 35 pm" src="https://cloud.githubusercontent.com/assets/2048618/18149282/8a2ec484-6f9c-11e6-9225-ad2bdb7dfbca.png">
Just prior to grabbing the above screenshots, I updated to the latest code (as of today) and restarted all RackHD services using the following one-liner:
ubuntu@rackhd1:~/src$ ./scripts/clean_all.bash && ./scripts/reset_submodules.bash && ./scripts/link_install_locally.bash && for i in http dhcp-proxy syslog taskgraph tftp; do sudo service on-${i} restart; done

Please let me know if I can provide any additional information to help move this forward.
Thanks,
Tim

**Comment by heckj** [comment] 2016-08-31 23:09
@anhou I know you've been working on the decoupling of dhcp and the workflows, wasn't sure how you'd tackled getting updates for nodes into the lookup system when those systems weren't available. It's looking like Tim's system here isn't in the lookup table and that's causing cascading failures. I'm thinking something in iPXE profile that we use to boot/install the OS might do the right thing with an extra POST to /api/lookups/ or something, but wanted to check with you. 

Thread related to this bug is from the RackHD slack channel on Aug 31 - search for `tgelter` and your name being mentioned ;-)

**Comment by tgelter** [comment] 2016-08-31 23:14
Per request, here are some additional details, in case they're helpful:

The RackHD server in question is a virtual machine located in a separate VLAN from the physical node being provisioned. Both are connected to the same physical switching infrastructure, however. If there's any particular connectivity checks you'd like me to run, please let me know.

Here's my configuration file: https://gist.github.com/tgelter/9ad7178dfad82032a270fcaff96236b8

**Comment by yyscamper** [comment] 2016-09-02 03:53
@tgelter : could you please attach the on-http log, so it will help use to understand the root case.

**Comment by anhou** [comment] 2016-09-02 13:54
Thanks @heckj forwarding this message! it indeed had many messages in slack, and have to use search to find @ me place :-)
Recent DHCP decoupling, just move  set lookup action to GET /profiles stage, it wouldn't miss setting lookup.  OS or node's every reboot and pxe boot would  lead to setting lookup because every time iPXE would call GET /profile API. for this issue of get template failure, it has several possibilities, no lookup or no workflow would cause this issue. 
so @tgelter could you help check things below? it will help a lot to root cause.
1. the IP address is set static in your os installation? Is there a IP change before and after OS installation?
2. use `curl localhost:8080/api/2.0/lookups | python -mjson.tool`  to get the output. and remember to confidential IP address you think.
3. on-http's log just as @yyscamper mentioned. and also on-dhcp-proxy's related mac address 's log is also helpful.

**Comment by tgelter** [comment] 2016-09-02 14:03
@yyscamper, here's the on-http log for the time period of the testing:
https://gist.github.com/tgelter/2866f8321500dbf892fa9f3196d23dce

**Comment by tgelter** [comment] 2016-09-02 14:38
@anhou here's the lookups after another attempt, this time using the static IP:
https://gist.github.com/tgelter/c7a012a2f823a981850168076ba0574e
The lookup still has the dynamic IP (10.30.20.244), rather than the static IP (10.27.16.55).
The CoreOS installation has configured the static IP as directed, and is pingable from the rackhd server:
`ubuntu@rackhd1:~$ ping 10.27.16.55  
PING 10.27.16.55 (10.27.16.55) 56(84) bytes of data.
64 bytes from 10.27.16.55: icmp_seq=1 ttl=63 time=0.161 ms
64 bytes from 10.27.16.55: icmp_seq=2 ttl=63 time=0.178 ms
64 bytes from 10.27.16.55: icmp_seq=3 ttl=63 time=0.175 ms
^C
--- 10.27.16.55 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.161/0.171/0.178/0.013 ms`

Here is the updated on-http.log:
https://gist.github.com/tgelter/a3a40e81f2eeed477c2435bc6c6085d1

Is there anything else I can provide to assist in finding root cause?

**Comment by tgelter** [comment] 2016-09-02 14:45
Also, it appears that the node is able to pull the lookups data:
<img width="744" alt="screen shot 2016-09-02 at 8 44 07 am" src="https://cloud.githubusercontent.com/assets/2048618/18207703/7e77c426-70e9-11e6-9ff6-3865c9225409.png">

**Comment by anhou** [comment] 2016-09-06 08:47
@tgelter 
1) Either in previous on-http.log https://gist.github.com/tgelter/2866f8321500dbf892fa9f3196d23dce or in another attempt's on-http.log  https://gist.github.com/tgelter/a3a40e81f2eeed477c2435bc6c6085d1 the node's IP address is '10.27.16.204' , and all its requests are recorded in on-http.log. they indicated that after GET 'coreos_production_pxe.vmlinuz' and 'coreos_production_pxe_image.cpio.gz' requests are received. no other requests to URL '/api/current/templates/install-coreos.sh' , so it's not a RackHD internal error, it should be the problem that the request from coreos cannot reach the RackHD on-http service. so could you run GET '/lookups' API in node, or by other way to check if network is OK from node to RackHD? 
2). For lookup in previous or in your another attempt , they are the same that the node's IP  "ipAddress": "10.27.16.204", and  "macAddress": "4c:76:25:3f:7a:01". I think no problem here.
3) I'm not sure what's 'The lookup still has the dynamic IP (10.30.20.244), rather than the static IP (10.27.16.55).' in your 'another attempt'.  from the log the node IP should be '10.27.16.204'

4) I found that the IP '10.27.16.200'  in https://gist.github.com/tgelter/2866f8321500dbf892fa9f3196d23dce could download install-coreos.sh successfully. so where is '10.27.16.200', is it another node? from the request log of  '/api/2.0/?macAddress=4c:6:25:3f:7a:01' and your REST API in previous  screenshot below. 10.27.16.200 and 10.27.15,204 from the same node? 
![image](https://cloud.githubusercontent.com/assets/14013330/18265636/4d1aef76-7449-11e6-8bea-68db62d9a277.png)

**Comment by tgelter** [comment] 2016-09-09 07:20
Hello @anhou,

I've attempted the CoreOS installation both using the RackHD built-in cloud-config + DHCP IP configuration, as well as with a custom cloud-config which configures static IP configuration. In both cases, RackHD never marks the _Graph.InstallCoreOS_ workflow as complete. Is there a specific test I can run that would be helpful to you?
If so, please let me know the exact steps you'd like followed, and I'll be glad to get screenshots/logs/whatever else your way.

Thanks!
Tim

**Comment by tgelter** [comment] 2016-09-09 07:21
Apologies, the "close button" is too close to the "Comment" button. :-)

**Comment by anhou** [comment] 2016-09-21 14:40
@tgelter I'm so sorry for missing your reply due to busy for other things. in previous test logs/screenshots, I'm a little confused about these environments that I've mentioned in the comments 15 days ago. maybe it's complicated to understand.  so let's restart the steps for this issues so that make it more clear. let me provide more exact steps for things I need to confirm about this issue. 

1. a relative clean environments to reproduce this issue again.
    a. Just using dhcp, not static ip environment to reproduce this issue, which to avoid confusion
    b Using the latest master branch codes that should have include PR  https://github.com/RackHD/on-http/pull/459, which has fix os installation workflow completion url problem

2. check it succeed or not with latest codes and get all the records below: 
    a. on-http/on-taskgraph/on-syslog/on-dhcp-proxy/on-tftp 's logs
    b. the console's screenshot
    c. get the `ifconfig` and `curl <rackhd server>:9080/api/2.0/lookups | python -mjson.tool` results in coreos.

**Comment by tgelter** [comment] 2016-09-21 16:41
Hello @anhou,

1. a/b) I've upgraded code to the latest master branch, and have confirmed that the fixes included in PR RackHD/on-http#459 are applied to the system. Afterward, I triggered a vanilla (no static configuration) _Graph.InstallCoreOS_ workflow, which again never is marked as complete, although the CoreOS installation is complete, and the system is sitting at the CoreOS command-line.

2. a/b/c) You can find the requested log files linked below, and the screenshots shown here:
<img width="746" alt="screen shot 2016-09-21 at 10 26 45 am" src="https://cloud.githubusercontent.com/assets/2048618/18720004/0ac681f4-7fe7-11e6-9872-bb7c318eeb4b.png">
<img width="745" alt="screen shot 2016-09-21 at 10 26 22 am" src="https://cloud.githubusercontent.com/assets/2048618/18720005/0ad3d07a-7fe7-11e6-9b21-2f003ae75cdf.png">

https://gist.github.com/tgelter/6196a9375ce126841937af038058fe42 (on-dhcp-proxy.log)
https://gist.github.com/tgelter/1a8626549b63146a905733cc200224fa (on-http.log)
https://gist.github.com/tgelter/0fd4a2d46b15c11ba326908192eeb94d (on-syslog.log)
https://gist.github.com/tgelter/265573fd63a59b0d493ae2623231cf53 (on-taskgraph.log)
https://gist.github.com/tgelter/4a346a788e361ee377acab11e46d2f13 (on-tftp.log)

Please let me know how else I can assist.
Thanks!
Tim

**Comment by anhou** [comment] 2016-09-22 13:17
@tgelter Thanks for all these information, I've go through all the logs. from the logs, downloading install-coreos.sh is successful and there's no lookups issues, but install coreos workflow still didn't finish. so current issue  is not the same with what you've report that downloading 'install-coreos.sh' failed in the beginning.  Now this problem should be the same with the issue https://github.com/RackHD/RackHD/issues/403 @lanchongyizu reported. I'll assist him to identify and fix this issue locally. if there's  any progress, I'll update here or there.

**Comment by leoyjchang** [comment] 2016-11-22 09:44
Same as https://github.com/RackHD/RackHD/issues/403 which has been resolved in latest RackHD. Close this ticket.

**Closed by leoyjchang** 2016-11-22 09:44 UTC
Labels: bug
