### ISSUE TITLE
After delete a tag, the tag is still exist in the node associated to the tag.

### ISSUE THREAD

**Issue by nortonluo** [RackHD/RackHD#185] opened 2016-04-18 06:33 UTC
I tried create a few tags to match with node B.  Then I delete these tags. I found although it is clear in tag list. But in NodeB, the tag name still exist. It can be seen in.
`curl http://10.240.19.38:8080/api/1.1/nodes/{NodeB}/tags `

@yyscamper @zyoung51 @amymullins @uppalk1

**Comment by zyoung51** [comment] 2016-04-18 13:33
@nortonluo This is by design and is documented: http://rackhd.readthedocs.org/en/latest/rackhd/index.html?highlight=tags#workflow-tag-support "Tags that are currently assigned to a node are not automatically removed from nodes when the rules backing a tag are deleted."

The tag management is really done by the layer above RackHD not be RackHD itself.  RackHD provides tag rules as a convenience to auto-tag nodes as they are discovered.  @uppalk1 recently added the master delete option, and that should be used by layers above RackHD if they want all instances of a tag removed.

**Closed by zyoung51** 2016-04-18 13:33 UTC

**Comment by nortonluo** [comment] 2016-04-21 10:16
What will happen if Tag is created and then deleted and then a new tag with same name is created but with different rule?

**Comment by zyoung51** [comment] 2016-04-21 12:33
@nortonluo @RackHD/corecommitters  RackHD will obey what it is being told to do.  If the layer above is doing bad things (refusing to clean up after itself with master delete, arbitrarily changing definitions) then RackHD will still do as it is told.  

It seems like you have tags (arbitrarily created names, owned by the northbound layer and applied by rules only out of convenience.  Not used by RackHD) confused with skus (coupled to hardware specific behavior and used by RackHD).  If you are truly concerned about this, the correct fix is probably to delete the /tags route, the tags rules and only permit manual assignment.

**Comment by nortonluo** [comment] 2016-04-21 13:01
Just image this situation:D
1. Assume a stack with 1000 nodes or more, Create a tag "MyTag" which match node A ,node B, node D
2. Somebody delete the "MyTag" tag.
3. Now bad things begin: Nobody now know what "MyTag" tag is. And nobody know which nodes has been applied to unless search though the  all 1000 nodes
4. Another one create "MyTag" tag apply to node C,node E, node F, node A. Not sure what is the consequence of  NodeA? Will there be two tag with same name in the same node?If Another one then delete "MyTag"  in NodeA. Will the tag be deleted twice? 
5.

**Comment by zyoung51** [comment] 2016-04-21 13:23
Assume a stack of 1000 nodes or a billion...  Create a tag which matches them all and then delete the tag rule.  Why are the nodes no longer the same label?  The tag is an arbitrary name assigned by infrastructure.  How can RackHD guess that it should remove them just because the rule is deleted?  Maybe the infrastructure just doesn't want new nodes to get that tag anymore but they want the existing ones to remain tagged.  How do you know what every infrastructure layer wants and why would you dictate that all infrastructure layers must work the way that you want?  

If the infrastructure layer wants tags removed, it needs to explicitly let RackHD know that by manually removing them; that is what the manual tag delete and the manual tag delete all are for.  Going to /tags/:name/nodes will return all the nodes with a tag assigned regardless of if that tag was assigned via a rule or manually or if the rule still exists.

**Comment by amymullins** [comment] 2016-04-21 16:45
@nortonluo , when deleting the tag from "the list" as you mention above only the tag rule is removed and the tag persists on the node.  There is support to remove a tag from a single node and more recently there was an enhancement that came out of the sprint review to delete a tag from all nodes with that particular tag.  Are you looking for a new enhancement to this feature that would delete a tag from a specific set of nodes?
.

**Comment by nortonluo** [comment] 2016-04-22 03:09
@amymullins  Yes, The enhancement to delete a tag from all nodes with a particular tag is just I'm looking for. That will make the tag API more complete.

**Comment by yyscamper** [comment] 2016-04-22 03:40
@amymullins @zyoung51 : 
I also had the same confusion of @nortonluo before, I think about some reason why user is tend to have such confusion:

(1) The tag rule is so similar with the sku rule, so user tends to confuse if the tag doesn't behave the same way with sku.
(2) The api name is not so good, it is a little strange that the tag is still there after `delete /tags/:name`, but actually what we delete is the **tag rule**, not the tag name itself, because  the tag name is still persistent to node.

My understanding is that the tag can be created/deleted manually for a node, actually a tag may not be bind with any rule. We introduce the tag rule is just want to bring some convenience to upper layer to batch create (**doesn't include delete**)  tag for multiple nodes.

I have some proposals to reduce the confusion:
(1) Distinguish the `Tag` and the `Tag Rule`:
    * `Tag` is only a string name, it is bind to one or more nodes, each `Tag` has **unique name**.
    * `Tag Rule` is a way that leverages catalog to automatically operate on `Tag`. Each `Tag Rule` has **unique identifier**, different `Tag Rule` may operate on the same `Tag`.
(2) Change some of the tag API names, to distinguish the tag and its rule:
```
//Create a new Tag Rule
post /tags  --> post /tags/rules (or post /tagrules)

//Delete a Tag Rule
delete /tags/:name  -->  delete /tags/rules/:identifier or (post /tagrules/:identifier)
```
Other API can remain the same to use the `tag`
```
get /tags    //return all Tags (including the *manually* created ones and those *auto* created ones via Tag Rule)
get /tags/:name/nodes  //return all nodes that has the specified tag.
post /tags/:name/nodes/workflows   // run a workflow on all nodes with the specified tag.
```

And create a new API to delete a tag from all nodes with a particular tag:
```
delete /tags/:name
```

**Comment by amymullins** [comment] 2016-04-22 18:38
@nortonluo there is a story that we may want to pend this effort on in the Stryker backlog (https://www.pivotaltracker.com/n/projects/1496834/stories/116774535).  This would allow us to use the current API with a query string and give the flexibility to define a set of nodes to delete a tag from.
FYI @brianparry
