### ISSUE TITLE
Problem with on-http auth-service-spec.js

### ISSUE THREAD

**Issue by dalebremner** [RackHD/RackHD#195] opened 2016-04-21 18:56 UTC
After adding new files route unit tests, the following error is output from: https://github.com/RackHD/on-http/blob/master/spec/lib/services/auth-service-spec.js#L346

Possible race condition due to lack of promise handling

--------------------------------------------

  653 passing (2m)
  4 pending
  1 failing

  1) Auth.Service Token should not expire as expected "before all" hook: start https server expiration set to 1 second:
     Error: Not running
      at Server.close (net.js:1233:11)
      at HttpService.stop (lib/services/http-service.js:131:28)
      at spec/lib/services/auth-service-spec.js:354:31
      at b (domain.js:183:18)
      at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
      at Promise._settlePromises (node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
      at Async.drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)

**Comment by cgx027** [comment] 2016-04-22 07:30
Hi @dalebremner , I am not able to reproduce the error but I do find some defects in the code. PR #248 is submitted to fix this.

**Comment by dalebremner** [comment] 2016-04-22 14:57
Hi Ted. Thanks for working on this. I ran npm test with your changes, but I still get the error above. You should be able to reproduce the problem by running npm test on this branch: https://github.com/dalebremner/on-http/tree/files

**Comment by cgx027** [comment] 2016-04-26 05:25
Hi @dalebremner , I tried your branch but still not able to hit the error. 

The log look like:
```
  Auth.Service
    Auth.Service
      â should return a token from /login (82ms)
      â should able to access with correct token in query string
      â should fail with wrong token in query string
      â should fail with empty token in query string
      â should fail with wrong token key in query string
      â should able to access with correct token in query header
      â should fail with wrong token in query header
      â should fail with empty token in query header
      â should fail with wrong token key in query header
      â should able to access with correct token in query body
      â should fail with wrong token in query body
      â should fail with empty token in query body
      â should fail with wrong token key in query body
      â should fail with no token at all
    Should return internal server error with auth error callback
      â should fail with auth
    Corrupted hash from config
      â Should throw exception with wrong length of hash from config
    Corrupted salt from config
      â Should throw exception with wrong length of salt from config
    Token expiration from config is not a number
      â Should throw exception with wrong length of salt from config
    Token should expire as expected
      â should return a token from /login (43ms)
      â Should get token expire error (1009ms)
    Token should not expire as expected
      â should return a token from /login (40ms)
      â should able to access with correct token in query string
      â Should still able to access after certain time (1015ms)
    Should fail with crypto errors
      â should fail accessing /login with internal error
    Should fail with token signature errors
      â should return a token from /login (40ms)
      â Should get token expire error

```

With help from @yyscamper , I added another commit to PR #248 to fix more Promise related defects.

**Comment by dalebremner** [comment] 2016-04-26 13:25
Thanks @cgx027 ! It's working now...

**Comment by cgx027** [comment] 2016-04-27 01:29
Cheers :+1: Thanks Dale for trying that.

**Comment by amymullins** [comment] 2016-05-03 17:38
Closing this out, confirmed it is no longer an issue.

**Closed by amymullins** 2016-05-03 17:38 UTC
Labels: bug
