### ISSUE TITLE
BIOS Image download graph hangs during the workflow - leaves the node hung up

### ISSUE THREAD

**Issue by hohene** [RackHD/RackHD#140] opened 2016-03-16 22:27 UTC
See internal ODR-597.
When we perform a BIOSImage to the node, the node gets stuck part way through the update at the screen shot attached - showing last line is "Stopping userspace bootsplash".
Tested on our releases 1.00, 1.1, both work ok.

```
https://---/redfish/v1/Systems/56e5e71a03791fa907aec37d/OEM/OnRack/Actions/BIOSImage
{ "filename": "S2S_3A14.BIN" }

{
"@odata.type": "#Task_1_0_0.Task",
"Name": "Flash Quanta BIOS",
"TaskState": "Pending",
"Messages": [],
"@odata.id": "/redfish/v1/TaskService/Tasks/65cc2254-3a56-4dff-9b46-4894ad3a7f61",
"@odata.context": null,
"TaskStatus": "OK",
"StartTime": "2016-03-14T01:47:31.168Z",
"Description": "",
"EndTime": "2016-03-14T01:47:31.168Z",
"Id": "65cc2254-3a56-4dff-9b46-4894ad3a7f61",
"Oem":
{ "SystemId": "56e5e71a03791fa907aec37d" }

}
```
The task stays in pending and the node stays 'stuck' (we let it sit overnight) until I hit a ctrl-alt-del at the kvm window. From there the node continues to boot, firmware does not get upgraded, and we get a failed task back.
full task logs on the internal bug.  
```
module:  Job.Catalogs.ProvideData
name:    ProvideCatalogDataJob
options:
  source: ami
  path:   systemRomId
taskId:  e55bfb00-004d-46ab-9bb1-0f874a596ee3
target:  56e5e72503791fa907aec387
[error] [2016-03-14T15:08:58.326Z] [on-taskgraph] [Task.Task] [Server] Task failed
 -> /node_modules/on-tasks/lib/task.js:261
error:          Error: Could not find a catalog entry for ami
taskId:         e55bfb00-004d-46ab-9bb1-0f874a596ee3
graphId:        de2a3164-f996-46b0-b0b8-fb79b43dcabc
injectableName: Task.Catalogs.Provide.Ami.BiosVersion
node:           56e5e72503791fa907aec387
[info] [2016-03-14T15:08:58.331Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
 -> /lib/task-runner.js:296
instanceId:   e55bfb00-004d-46ab-9bb1-0f874a596ee3
state:        failed
taskRunnerId: 5e768d95-49f2-4a90-b245-457e6ea3a869
[debug] [2016-03-14T15:08:58.334Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Listener received task finished event, triggering evaluation
 -> /lib/task-scheduler.js:525
data:
  taskId:           e55bfb00-004d-46ab-9bb1-0f874a596ee3
  graphId:          de2a3164-f996-46b0-b0b8-fb79b43dcabc
  state:            failed
  error:
    """
      Error: Could not find a catalog entry for ami
          at /var/renasar/on-taskgraph/node_modules/on-tasks/lib/jobs/provide-catalog-data.js:67:23
          at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
          at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
          at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
          at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:128:12)
          at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
          at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
          at process._tickDomainCallback (node.js:459:13)
    """
  context:
```

**Comment by heckj** [comment] 2016-03-18 19:00
FYI @leoyjchang

**Comment by yyscamper** [comment] 2016-03-22 15:14
@hohene : 
For quanta BIOS update, it needs a special overlayfs because it needs some specified tools, so could you please first confirm you have used the correct overlayfs?

**Comment by hohene** [comment] 2016-04-14 15:01
We are still hitting this issue.  Here's comments from the ODR - please see the ODR 597 for the latest logs.
 Per Felix last round of comments:
 tried on another Quanta, it has the same issue. I guess it may be due to following reason:
(1) We built a wrong overlayfs, the ami tools are broken. The probability is relative low because we should have use the same build procedure.
(2) The compatibility issue between the kernel and overlayfs. Because I see the microkernl kernel and fs is v3.16, but the overlayfs version that used in flash-quanta-bios is v3.13.

Hou, Andrew Heck, Joseph Broderick Phillips, Ben do you have any insight on this?

   options: {
        kernelFile: 'vmlinuz-3.16.0-25-generic',
        initrdFile: 'initrd.img-3.16.0-25-generic',
        kernelUri: '{{ api.server }}/common/{{ options.kernelFile }}',
        initrdUri: '{{ api.server }}/common/{{ options.initrdFile }}',
        basefs: 'common/base.trusty.3.16.0-25-generic.squashfs.img',
        overlayfs: 'common/discovery.overlay.cpio.gz',
        profile: 'linux.ipxe',
        comport: 'ttyS0'
    },

"bootstrap-ubuntu": {
            "basefs": "common/base.trusty.3.13.0-32.squashfs.img",
            "overlayfs": "common/overlayfs_quanta_t41_flash-v1.1-3.13.0-32.cpio.gz"
        },
}

**Comment by hohene** [comment] 2016-04-14 15:49
We ran the test again using code base from 4/13/2016 for the last round of testing.

**Comment by zyoung51** [comment] 2016-04-14 15:54
@yyscamper @hohene: If it helps, the Quanta BIOS firmware upgrade was retooled: https://github.com/RackHD/on-skupack/tree/master/quanta-t41 and no longer requires the overlayfs.  The updated afulnx_64 included in the newer BIOS packages no longer has the runtime dependency to build a driver.

There is an open issue with the download files task not functioning: https://github.com/RackHD/on-http/issues/215, so once you get past the catalog issue you should encounter that failure with the 4/13/2016 build.

**Comment by heckj** [comment] 2016-04-14 16:08
@hohene ^^ this won't help you with the 1.2 release work you're doing though, since we're not immediately incorporating SKU pack support into it. This refactor work is going to be effective in some  release after 1.2...

**Comment by zyoung51** [comment] 2016-04-14 16:59
In the current images the overlayfs is missing the necessary files for the bundled afulnx_64 version to build the driver that it needs.  You may want to switch to the newer afulnx_64 binary that was used for the skupack work.

**Comment by zyoung51** [comment] 2016-04-15 13:50
@hohene: If you are using the latest code, you also need to wait for this to go in: https://github.com/RackHD/on-http/pull/230.  After you get past the hangup caused by the afulnx binary in the 3.13 overlays, you will have an issue with the images being inaccessible.  The commit above re-exposes the files/md5sums on the southbound side.

**Comment by amymullins** [comment] 2016-06-09 13:26
@hohene ODR reference 597 has been closed out.  Is this github issue ready for closure as well?

**Comment by amymullins** [comment] 2016-06-09 14:25
Closing out issue, ODR-597 is no longer open.

**Closed by amymullins** 2016-06-09 14:25 UTC
Labels: bug
