### ISSUE TITLE
failed to run unit test for on-http

### ISSUE THREAD

**Issue by PengTian0** [RackHD/RackHD#259] opened 2016-06-07 08:16 UTC
when run unit test for on-http on two machines , I got different results. One machine show 13 failing, and the other one show no failing.

The difference is the sortorder of the result of command  "find spec/lib/api/2.0 -name '*-spec.js' " .
If the test order as below, the unit-test will fail:
```
spec/lib/api/2.0/workflows-spec.js
spec/lib/api/2.0/obms-spec.js
spec/lib/api/2.0/profiles-spec.js
spec/lib/api/2.0/files-spec.js
spec/lib/api/2.0/tasks-spec.js
spec/lib/api/2.0/pollers-spec.js
spec/lib/api/2.0/nodes-spec.js
```

If the test order as below, the result is passing:
```
spec/lib/api/2.0/obms-spec.js
spec/lib/api/2.0/profiles-spec.js
spec/lib/api/2.0/files-spec.js
spec/lib/api/2.0/tasks-spec.js
spec/lib/api/2.0/pollers-spec.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/api/2.0/workflows-spec.js
```

here is the failing logs :
```
768 passing (2m)
3 pending 
13 failing

  1) Http.Api.Profiles 2.0 GET /profiles/metadata should return a list of profiles:
     expected 200 "OK", got 500 "Internal Server Error"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  2) Http.Api.Profiles 2.0 GET /profiles/metadata/:name should return a single profile:
     expected 200 "OK", got 500 "Internal Server Error"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  3) Http.Api.Tasks GET /tasks/:id should send down tasks:
     expected 200 "OK", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  4) Http.Api.Obms should return a list of obm service types:
     expected 200 "OK", got 500 "Internal Server Error"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  5) Http.Api.Obms should get the ipmi obm service type:
     expected 200 "OK", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  6) Http.Api.Obms should get the panduit obm service type:
     expected 200 "OK", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  7) Http.Api.Internal.Files "before all" hook: start HTTP server and add file:
     expected 200 "OK", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  8) Http.Api.Pollers should create an IPMI poller with POST /pollers:
     expected 201 "Created", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 201 "Created", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 201 "Created", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  9) Http.Api.Pollers should create an SNMP poller with POST /pollers:
     expected 201 "Created", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 201 "Created", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 201 "Created", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  10) Http.Api.Pollers POST /pollers afterwards "before each" hook for "should contain the new poller in GET /pollers":
     expected 201 "Created", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 201 "Created", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 201 "Created", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  11) Http.Api.Nodes 2.0 GET /nodes should return a list of nodes:
     expected 200 "OK", got 500 "Internal Server Error"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  12) Http.Api.Nodes GET /nodes/:id should return a single node:
     expected 200 "OK", got 400 "Bad Request"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 400 "Bad Request"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 400 "Bad Request"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16

  13) Http.Api.Nodes GET /nodes/:identifier/obm should return a list of the node's OBM settings:
     expected 200 "OK", got 500 "Internal Server Error"
Response body:
{ message: 'Cannot call method \'find\' of undefined' }
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/onrack/test/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/onrack/test/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/onrack/test/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)
  Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at _stream_readable.js:944:16
```

**Comment by yyscamper** [comment] 2016-06-07 08:29
@WangWinson and me had some initial debug on this issue, below is our finding:

- Run profiles 2.0 API and workflows 2.0 API test individually will both pass:
```
./node_modules/mocha/bin/_mocha spec/lib/api/2.0/profiles-spec.js  --require spec/helper.js
``` 
```
./node_modules/mocha/bin/_mocha spec/lib/api/2.0/workflows-spec.js  --require spec/helper.js
```

- First profiles, then workflows API unit-test will still pass:
```
./node_modules/mocha/bin/_mocha spec/lib/api/2.0/profiles-spec.js spec/lib/api/2.0/workflows-spec.js  --require spec/helper.js
```

- First workflows API, then profiles API unit-test will **fail**:
```
./node_modules/mocha/bin/_mocha spec/lib/api/2.0/workflows-spec.js spec/lib/api/2.0/profiles-spec.js --require spec/helper.js
```

The failure log:
```
 29 passing (5s)
  2 failing

  1) Http.Api.Profiles 2.0 GET /profiles/metadata should return a list of profiles:
     expected 200 "OK", got 500 "Internal Server Error"
Response body:
{ message: 'Cannot read property \'find\' of undefined' }
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/yuanf/src/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/yuanf/src/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/yuanf/src/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
  Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at endReadableNT (_stream_readable.js:913:12)

  2) Http.Api.Profiles 2.0 GET /profiles/metadata/:name should return a single profile:
     expected 200 "OK", got 500 "Internal Server Error"
Response body:
{ message: 'Cannot read property \'find\' of undefined' }
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Test._assertStatus (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:148:18)
    at assert (/home/yuanf/src/on-http/node_modules/supertest/lib/test.js:127:12)
    at /home/yuanf/src/on-http/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/home/yuanf/src/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
    at IncomingMessage.<anonymous> (/home/yuanf/src/on-http/node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
  Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at endReadableNT (_stream_readable.js:913:12)
```

**Comment by yyscamper** [comment] 2016-06-07 08:51
The unit-test error that depends on the execution order is very similar with a bug @WangWinson had fixed in this PR (https://github.com/RackHD/on-http/pull/273), the root cause is at this line (https://github.com/RackHD/on-http/pull/273/files#diff-9c2b1f4182b01a1dca0072e663061bd8L7):
the code defined a global router, so whenever we run the `helper.startServer()` and stub on it, the router will be called twice for following logic:
```
router.get('/files', function(...))  #1, triggered by other test cases
// do some stubs
router.get('/files', function(...)) #2, triggered by the files api unit-test
```

Our stub only takes effect on #2, but the previous routing callback will take precedent if there is same routing uri. so whenever we do stub, the unit-test will always go to the #1 and run with the non-stub logic.

The fix is very simple, just move the router to a local one: https://github.com/RackHD/on-http/pull/273/files#diff-9c2b1f4182b01a1dca0072e663061bd8R25

I guess the swagger API 2.0 design has similar defect.

**Comment by PengTian0** [comment] 2016-06-07 08:51
if the test order as below, the result is passing:
_spec/lib/api/2.0/config-spec.js_
spec/lib/api/2.0/workflows-spec.js
spec/lib/api/2.0/obms-spec.js
spec/lib/api/2.0/profiles-spec.js
spec/lib/api/2.0/files-spec.js
spec/lib/api/2.0/tasks-spec.js
spec/lib/api/2.0/pollers-spec.js
spec/lib/api/2.0/nodes-spec.js

**Comment by yyscamper** [comment] 2016-06-07 08:53
@brianparry: you are most familiar with the the API 2.0 code architecture, do you have any insight on this?

I think the expected behavior is every unit-test file is independent, it should never depend on its execution order

**Comment by brianparry** [comment] 2016-06-07 17:33
@yyscamper I've seen this type of thing happen when globally accessible things (injected singletons) are at least partially mocked, and then not restored when tests exit.  There is certainly no intentional dependency between tests, but there may be places where order matters because tests are cleaning up after themselves.  In this particular instance, it looks like one of the expected waterline collections is missing.

**Comment by brianparry** [comment] 2016-06-07 17:59
@BillyAbildgaard Is going to look into this.

**Comment by amymullins** [comment] 2016-06-07 18:01
Tracking story; https://www.pivotaltracker.com/projects/1496834/stories/121068797

**Comment by yyscamper** [comment] 2016-06-13 03:54
I have opened a discussion in google group to enable the randomize unit-testing, so that we can uncover this kind of problem earlier: https://groups.google.com/forum/#!topic/rackhd/OoZfzsE12gc

**Closed** 2016-06-30 18:28 UTC
Labels: bug
