### ISSUE TITLE
Docker Hub Auto Build failed for a month..

### ISSUE THREAD

**Issue by panpan0000** [RackHD/RackHD#427] opened 2016-09-22 07:25 UTC
https://hub.docker.com/r/rackhd/on-http/builds/
https://hub.docker.com/r/rackhd/on-taskgraph/builds/

@rolandpoulter

**Comment by zyoung51** [comment] 2016-09-22 12:34
This looks like a duplicate of https://github.com/RackHD/RackHD/issues/393

**Comment by heckj** [comment] 2016-09-22 15:10
Yes, it is.

**Closed by heckj** 2016-09-22 15:10 UTC
