### ISSUE TITLE
on-taskgraph unit tests instability

### ISSUE THREAD

**Issue by BillyAbildgaard** [RackHD/RackHD#351] opened 2016-07-29 15:38 UTC
The on-taskgraph unit tests seem to be unstable.  Upon filing a pull request for a few changes to only the README Travis failed three consecutive times before finally passing.  Timeout errors on "before all" hooks

https://github.com/RackHD/on-taskgraph/pull/148

**Comment by heckj** [comment] 2016-07-29 18:54
@BillyAbildgaard tests on jenkins, or in travis, timing out? Couldn't tell from the merged PR after it was merged...

**Comment by BillyAbildgaard** [comment] 2016-07-29 18:56
@heckj timing out was in travis.  I unfortunately didn't take a screenshot before the tests re-ran and passed on the third attempt

**Comment by heckj** [comment] 2016-07-29 18:58
coolio - thanks sir, I'm kicking some local builds (relatively resource unconstrained) on my local machine to see if I can repro, and i'll poke at what Travis is doing if I can't get it here

**Comment by heckj** [comment] 2016-07-29 19:08
reproduced - and I've seen this before. Logs from the failed build at https://api.travis-ci.org/jobs/148398773/log.txt?deansi=true

- using node v4.4.7 (npm v2.15.8)

Two failed tests - although this failure is intermittent, and I don't have a solid reproducible case on my own laptop:

```
  1) Graph Library "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
      at Promise._settlePromises (node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)

  2) Task Runner createHeartbeatSubscription should heartbeat Tasks on an interval:

      AssertionError: expected 6 to equal 5
      + expected - actual

      -6
      +5
      
      at spec/lib/task-runner-spec.js:256:68
      at AnonymousObserver._onCompleted (spec/lib/task-runner-spec.js:50:17)
      at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (node_modules/on-core/node_modules/rx/dist/rx.js:1802:12)
      at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/on-core/node_modules/rx/dist/rx.js:1741:14)
      at AnonymousObserver.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/on-core/node_modules/rx/dist/rx.js:5807:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/on-core/node_modules/rx/dist/rx.js:1741:14)
      at Object.InnerObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:5538:33)
      at Object.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at AutoDetachObserverPrototype.next (node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at CatchObserver.next (node_modules/on-core/node_modules/rx/dist/rx.js:3292:59)
      at CatchObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at CatchObserver.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at AutoDetachObserverPrototype.next (node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at InnerObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:3850:90)
      at InnerObserver.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at AutoDetachObserverPrototype.next (node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at scheduleItem (node_modules/on-core/node_modules/rx/dist/rx.js:3075:16)
      at JustSink.run (node_modules/on-core/node_modules/rx/dist/rx.js:3083:9)
      at JustObservable.subscribeCore (node_modules/on-core/node_modules/rx/dist/rx.js:3064:19)
      at JustObservable.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at setDisposable [as action] (node_modules/on-core/node_modules/rx/dist/rx.js:2038:46)
      at ScheduledItem.invokeCore (node_modules/on-core/node_modules/rx/dist/rx.js:874:33)
      at ScheduledItem.invoke (node_modules/on-core/node_modules/rx/dist/rx.js:862:40)
      at runTrampoline (node_modules/on-core/node_modules/rx/dist/rx.js:1103:37)
      at tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at CurrentThreadScheduler.schedule (node_modules/on-core/node_modules/rx/dist/rx.js:1119:45)
      at JustObservable.Rx.ObservableBase.ObservableBase._subscribe (node_modules/on-core/node_modules/rx/dist/rx.js:2051:32)
      at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (node_modules/on-core/node_modules/rx/dist/rx.js:1990:19)
      at MergeAllObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:3819:37)
      at MergeAllObserver.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at AutoDetachObserverPrototype.next (node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (node_modules/on-core/node_modules/rx/dist/rx.js:2101:14)
      at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at InnerObserver.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at AutoDetachObserverPrototype.next (node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at InnerObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:3850:90)
      at InnerObserver.tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at AutoDetachObserverPrototype.next (node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
      at scheduleNext (node_modules/on-core/node_modules/rx/dist/rx.js:2407:9)
      at schedule (node_modules/on-core/node_modules/rx/dist/rx.js:1290:79)
      at tryCatcher (node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
      at runTask (node_modules/on-core/node_modules/rx/dist/rx.js:1174:38)
      at Immediate._onImmediate (node_modules/on-core/node_modules/rx/dist/rx.js:1208:36)
```

**Comment by heckj** [comment] 2016-07-29 19:21
second repro https://api.travis-ci.org/jobs/148403094/log.txt?deansi=true.

Second repro was just the before_all hook:

```
  1) Graph Library "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
      at Promise._settlePromises (node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
```

Node 4 is what's failing here, not node 6 interestingly... Updated the PR used to repro with a C compiler to see if that made an issue with the node4 installation. Apparently not, since this immediately reproduced even with that added

**Comment by yyscamper** [comment] 2016-09-02 06:06
@BillyAbildgaard @heckj : I believe this issue will be fixed by my PR: https://github.com/RackHD/on-taskgraph/pull/166 though it looks like a workaround.

**Comment by benbp** [comment] 2016-12-13 20:57
Re-opening because this issue still exists (but should be resolved by https://github.com/RackHD/on-taskgraph/pull/191).

**Closed** 2016-12-13 21:55 UTC
Labels: bug
